dependencies:
- name: exposecontroller
  version: 2.3.118
  repository: http://chartmuseum.jenkins-x.io
  alias: expose
- name: exposecontroller
  version: 2.3.118
  repository: http://chartmuseum.jenkins-x.io
  alias: cleanup
- name: foxsports-platform-general-test-conductor-workers
  repository: https://artifactory.cluster.foxsports.foxsports-gitops-prod.com.au/artifactory/helm
  alias: test-conductor-workers
  version: 1.0.1
